
export LANG=en_US
xdg-user-dirs-gtk-update
export LANG=zh_CN.UTF-8

sudo dnf install alacritty fish neovim fd-find repgrep go rust cargo rustup

wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
sudo cp JetBrainsMonoNerdFont-* /usr/share/fonts/
sudo fc-cache -f -v


wget https://repo.trojan-cdn.com/clash-verge-rev/Clash%20Verge%20Rev%20v1.7.5/clash-verge-1.7.5-1.x86_64.rpm


git clone https://github.com/NvChad/starter ~/.config/nvim && nvim


